org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21
enabled_platforms=fabric,forge

archives_base_name=zigysmultiloaderutils
mod_id=zigysmultiloaderutils
mod_version=1.3.0
maven_group=zigy.zigysmultiloaderutils

fabric_loader_version=0.15.11
fabric_api_version=0.100.6+1.21

neoforge_version=21.0.114-beta
parchment_version=2024.07.07