modLoader = "javafml"
loaderVersion = "[20.4.225,)"
#issueTrackerURL = ""
license = "MIT License"

[[mixins]]
config = "zigysmultiloaderutils-common.mixins.json"
[[mixins]]
config = "zigysmultiloaderutils.mixins.json"

[[mods]]
modId = "zigysmultiloaderutils"
version = "${version}"
displayName = "Zigy's Multiloader Utils"
authors = "Zigy"
description = '''
Pretty self explanatory.
'''
#logoFile = ""

[[dependencies.zigysmultiloaderutils]]
modId = "neoforge"
type="required"
versionRange = "[20.4.225,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zigysmultiloaderutils]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"