modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT License"

[[mixins]]
config = "zigysmultiloaderutils-common.mixins.json"
[[mixins]]
config = "zigysmultiloaderutils.mixins.json"

[[mods]]
modId = "zigysmultiloaderutils"
version="1.3.0"
displayName = "Zigy's Multiloader Utils"
authors = "Zigy"
description = '''
Pretty self explanatory.
'''
#logoFile = ""

[[dependencies.zigysmultiloaderutils]]
modId = "neoforge"
type="required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zigysmultiloaderutils]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"